GET http://localhost:3000/todos

###

GET http://localhost:3000/todos/60ba1021652c675f0190b92e

###

POST http://localhost:3000/todos
Content-Type: application/json

{
    "text": "Assignment 2"
}

###

DELETE http://localhost:3000/todos/60ba1021652c675f0190b92e